### ISSUE TITLE
Checkbox, Radio: avoid toggling on 'enter'

### ISSUE THREAD

**Issue by sohkai** [aragon/ui#626]
From https://github.com/aragon/aragon-ui/pull/620#discussion_r335479434:

> the behavior of Checkbox is wrong: the enter key should be used to submit forms (if any) when a checkbox is focused, not to toggle the checkbox itself ([reference](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/checkbox_role#Keyboard_interactions)).

**Comment by eliobricenov** [comment]
I can work on this.
