### ISSUE TITLE
TextInput: Wrong ref management

### ISSUE THREAD

**Issue by pakokrew** [aragon/ui#676]
It seems that there is a problem with ref registering on TextInput. 
I don't know where the problem exactly is, but the component used along with `react-hook-form` isn't registering correctly the field. 

Example here : https://codesandbox.io/s/react-hook-form-get-started-3n98s
(check the console)

**Comment by eliobricenov** [comment]
Hey @pakokrew  - Do we any steps to reproduce this?

**Comment by nivida** [comment]
I closed this issue because of the missing detailed description and also the missing answer to the question from @eliobricenov
